name: CHECK CI/CD
on:
  push:
    branches: [ master ]
jobs:
  buildWEB:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email jain.samvit@gmail.com
          git config --global user.name samvitjain
          git status
          git remote add origin https://${{secrets.COMMIT_TOKEN}}@github.com/samvitjain/peace.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
